"""Calibrate kappa (P_grid = kappa * P_peak), e_ref, d1, d2 and the reward scale from TRAIN days only (truthful reports, M0).

P_peak = median over train days of the daily peak total power if every vehicle charged at full rate on arrival.
For each kappa: share of occupied steps where that uncontrolled demand exceeds P_grid ("binding"), and mean unmet share U,
cost/kWh and wear proxy for FCFS/EDF/LLF and the offline optimum. Writes results/calibration_kappa.csv.
Also writes configs/derived_<site>_kappa<kappa>.yaml (P_peak, P_grid, e_ref, d1, d2, reward_scale) for the chosen kappa.
Usage: python scripts/calibrate.py [configs/base.yaml] [kappa=0.2]
"""
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, "src")
from safecharge.baselines import rule_action  # noqa: E402
from safecharge.config import get_days, load_config  # noqa: E402
from safecharge.data import DELTA, N_PORTS, P_PORT, T  # noqa: E402
from safecharge.env import ChargingEnv  # noqa: E402
from safecharge.metrics import rollout  # noqa: E402
from safecharge.offline_lp import solve_offline  # noqa: E402

M_PEN = 5.0  # $/kWh unmet-energy penalty in the offline LP (about 19x the peak price); PROVISIONAL, same value used in tests
cfg = load_config(sys.argv[1] if len(sys.argv) > 1 else "configs/base.yaml")
KAPPA = float(sys.argv[2]) if len(sys.argv) > 2 else 0.2
site = cfg["site"]
days = get_days(cfg, "train")


def demand_profile(d):
    x = np.zeros(T)
    for a, b in zip(d.arr, d.dep):
        x[a:b] += P_PORT
    return x


peaks = np.array([demand_profile(d).max() for d in days])
P_peak = float(np.median(peaks))
e_ref = float(np.mean(np.concatenate([d.energy for d in days])))
req_per_day = float(np.mean([d.energy.sum() for d in days]))
print(f"{site}: {len(days)} train days | P_peak(median daily peak, full-rate-on-arrival) = {P_peak:.1f} kW "
      f"(mean {peaks.mean():.1f}, max {peaks.max():.1f}; all ports = {N_PORTS[site] * P_PORT:.1f} kW)")
print(f"e_ref (mean e_i) = {e_ref:.2f} kWh; mean requested energy/day = {req_per_day:.0f} kWh; mean vehicles/day = {np.mean([len(d.arr) for d in days]):.1f}")

rows = []
for kappa in (0.15, 0.2, 0.25, 0.3, 0.4, 0.6, 1.0):
    Pg = kappa * P_peak
    env = ChargingEnv(N_PORTS[site], Pg, e_ref=e_ref)
    occ_steps = bind_steps = 0
    res = {k: [] for k in ("FCFS", "EDF", "LLF", "OPT")}
    for d in days:
        prof = demand_profile(d)
        occ_steps += int((prof > 0).sum())
        bind_steps += int((prof > Pg).sum())
        rep = d.dep.astype(float)
        for kind in ("FCFS", "EDF", "LLF"):
            m, _ = rollout(env, d, rep, lambda e, o, k=kind: rule_action(e, k))
            res[kind].append((m["unmet_share"], m["cost_per_kwh"], m["cost1_sum"] * e_ref, m["cost2_sum"], m["high_power_ratio"], m["cost"], m["kwh"]))
        lp = solve_offline(d, Pg, P_PORT, M_PEN)
        kwh = d.energy.sum() - lp["unmet"]
        res["OPT"].append((lp["unmet"] / d.energy.sum(), lp["cost"] / kwh if kwh > 0 else np.nan, lp["unmet"], np.nan, np.nan, lp["cost"], kwh))
    row = dict(kappa=kappa, P_grid=round(Pg, 1), binding_share=round(bind_steps / occ_steps, 3))
    for k, v in res.items():
        a = np.array(v, float)
        row[f"{k}_U"] = round(np.nanmean(a[:, 0]), 4)
        row[f"{k}_cost_per_kwh"] = round(np.nanmean(a[:, 1]), 4)
        row[f"{k}_c2_ep"] = round(np.nanmean(a[:, 3]), 3)
        row[f"{k}_W"] = round(np.nanmean(a[:, 4]), 3)
        row[f"{k}_cost_day"] = round(np.nanmean(a[:, 5]), 2)
    rows.append(row)
tab = pd.DataFrame(rows)
tab.to_csv("results/calibration_kappa.csv", index=False)
pd.set_option("display.width", 250)
print(tab[["kappa", "P_grid", "binding_share"] + [f"{k}_U" for k in ("FCFS", "EDF", "LLF", "OPT")]].to_string(index=False))
print(tab[["kappa"] + [f"{k}_cost_per_kwh" for k in ("FCFS", "EDF", "LLF", "OPT")] + [f"{k}_c2_ep" for k in ("FCFS", "EDF", "LLF")] + [f"{k}_W" for k in ("FCFS", "EDF", "LLF")]].to_string(index=False))

import yaml  # noqa: E402

row = tab[tab.kappa == KAPPA].iloc[0]
derived = dict(
    site=site, kappa=KAPPA, P_peak=round(P_peak, 2), P_grid=round(KAPPA * P_peak, 2), e_ref=round(e_ref, 3),
    d1=round(0.02 * req_per_day / e_ref, 4),   # 2% of requested energy, in c1 units (unmet kWh / e_ref per day)
    d2=round(float(np.mean([row[f"{k}_c2_ep"] for k in ("FCFS", "EDF", "LLF")])), 3),  # mean rule-baseline episode wear proxy (train, M0)
    reward_scale=round(float(row["FCFS_cost_day"]) / 10.0, 4),  # so a typical FCFS day returns about -10
    offline_penalty_M=M_PEN, n_train_days=len(days),
)
out = f"configs/derived_{site}_kappa{KAPPA}.yaml"
with open(out, "w") as f:
    f.write("# generated by scripts/calibrate.py from TRAIN days only; do not edit by hand\n")
    yaml.safe_dump(derived, f)
print("\nwrote", out, derived)
